apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: neo4jclusters.database.neo4j.org
spec:
  group: database.neo4j.org
  names:
    kind: Neo4jCluster
    listKind: Neo4jClusterList
    plural: neo4jclusters
    singular: neo4jcluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              adminPassword:
                type: string
              coreReplicas:
                type: integer
              hpa:
                type: object
                properties:
                  minReplicas:
                    type: integer
                  maxReplicas:
                    type: integer
              image:
                type: string
              persistence:
                type: object
                properties:
                  enabled:
                    type: boolean
                  size:
                    type: string
                  storageClass:
                    type: string
              readReplicaReplicas:
                type: integer
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
              service:
                type: object
                properties:
                  type:
                    type: string
                  ports:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        protocol:
                          type: string
                        port:
                          type: integer
                        targetPort:
                          type: integer
