apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: neo4j
  name: metacontroller-role
rules:
  - apiGroups: ["metacontroller.k8s.io"]
    resources: ["controllerrevisions", "decoratorcontrollers"]
    verbs: ["list", "get", "create", "delete", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metacontroller-rolebinding
  namespace: neo4j
subjects:
  - kind: ServiceAccount
    name: metacontroller
    namespace: neo4j
roleRef:
  kind: Role
  name: metacontroller-role
  apiGroup: rbac.authorization.k8s.io
