apiVersion: v1
kind: Service
metadata:
  name: neo4j-controller
  namespace: neo4j
spec:
  selector:
    app: neo4j-controller  # Match the labels in the Deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081   # Make sure the correct target port is used
